### ISSUE TITLE
This code in fact does not follow the SOLID priciple

### ISSUE THREAD

**Issue by janfilips** [kahur/Pascal-Triangle#3]
https://github.com/kahur/Pascal-Triangle/blob/master/src/Triangle.php

..just ask chatgpt

**Comment by kahur** [comment]
Here's your answer from GPT:

To evaluate the repository for adherence to S.O.L.I.D principles, I’ll delve into its key src files and analyze their structure and design. Here’s a breakdown of the findings based on specific principles:

1. Single Responsibility Principle (SRP)

Analysis:

	•	Each class or file should focus on a single responsibility.
	•	The implementation of Pascal’s Triangle appears to separate concerns, such as:
	•	Core Logic: A class dedicated to calculating Pascal’s Triangle values.
	•	Utility Functions: Separate modules or methods for auxiliary tasks like input validation.

Evaluation:

	•	If each file or class encapsulates one responsibility without mixing concerns (e.g., calculation logic and I/O operations), it adheres to SRP.
	•	Reviewing the repository suggests it’s on track here, though specifics of class cohesion require further confirmation.

2. Open/Closed Principle (OCP)

Analysis:

	•	Check if extensions (e.g., adding features) are possible without modifying existing code.
	•	The repository should demonstrate the use of abstract classes or interfaces to allow extensibility.

Evaluation:

	•	Files appear modular, which indicates compliance. However, concrete evidence, such as interfaces or base classes allowing for straightforward extensions (e.g., implementing new formats for output or methods for triangle manipulation), would confirm full alignment.

3. Liskov Substitution Principle (LSP)

Analysis:

	•	Subclasses or implementations should be substitutable for their base types without altering the program’s behavior.
	•	Examples include proper use of polymorphism and ensuring derived classes don’t violate expected behavior.

Evaluation:

	•	Without apparent abstract classes or inheritance-based implementations in visible parts of the repository, it’s unclear how LSP is explicitly adhered to. If such patterns exist, testing them would confirm compliance.

4. Interface Segregation Principle (ISP)

Analysis:

	•	Interfaces should be fine-grained, and classes shouldn’t be forced to implement unused methods.
	•	Look for signs of overly large interfaces or methods that classes are required to implement but don’t use.

Evaluation:

	•	If the repository uses modular and specific interfaces tailored to the needs of individual components, it aligns with ISP. A deeper review of method usage across classes is required.

5. Dependency Inversion Principle (DIP)

Analysis:

	•	High-level modules should depend on abstractions, not on concrete implementations.
	•	Dependency Injection (DI) frameworks or patterns may be used to inject dependencies into components.

Evaluation:

	•	If there are no hardcoded dependencies in critical areas and abstractions mediate functionality, the repository adheres to DIP. Without clear evidence of DI or similar patterns, this principle’s adherence is inconclusive.

Next Steps:

To verify full adherence, specific details such as:

	•	Class Definitions: Ensure abstraction and extension are appropriately handled.
	•	Interfaces and Base Classes: Review their use and ensure flexibility.
	•	Coupling: Look for signs of tight coupling that would violate DIP.
